### ISSUE TITLE
Edit LinkIt fieldtype values via front-end

### ISSUE THREAD

**Issue by seandelaney** [fruitstudios/LinkIt#6]
I'm using the LinkIt field type for storing members custom URL's. 

I want to allow members manage their custom URL's via the front-end in a profile update page.

Is it possible to edit LinkIt field values via the front-end?

**Comment by samhibberd** [comment]
I don's see any reason that your couldn't modify entries on the front end, you would just need to ensure the templates display the correct inputs and the correct values are posted.

We have completely rewritten the plugin which is due to be released shortly, no major changes to functionality, just improvements to the code base and the way data is stored and accessed, should make it easier to use on the front end too!
